// <auto-generated />
using EFCore2Playgrounds.ValueObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EFCore2Playgrounds.Migrations.ValueObjectDb
{
    [DbContext(typeof(ValueObjectDbContext))]
    partial class ValueObjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore2Playgrounds.ValueObject.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EFCore2Playgrounds.ValueObject.Post", b =>
                {
                    b.OwnsOne("EFCore2Playgrounds.ValueObject.Slug", "Slug", b1 =>
                        {
                            b1.Property<int>("PostId");

                            b1.Property<string>("Value");

                            b1.ToTable("Posts");

                            b1.HasOne("EFCore2Playgrounds.ValueObject.Post")
                                .WithOne("Slug")
                                .HasForeignKey("EFCore2Playgrounds.ValueObject.Slug", "PostId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
